config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :todo_lists do
    member do
      post 'add_todo_item'
      delete 'todo_item/:todo_item_id' => "todo_lists#destroy_todo_item", as: :todo_item
    end
  end
  resources :organizations
  resources :occasions do
    collection do
      get 'all'
    end
  end
  devise_for :users
  get "dashboard/" => "dashboard#index"
  get "fmodel/" => "fmodel#index"
  get "form_build/" => "form_build#index"
  root "welcome#index"

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  validates :organization, presence: true
  validates :user, presence: true
  validates :name, presence: true
  belongs_to :organization
  belongs_to :user
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
  before_action :set_occasion, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, except: [:all, :show, :index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  # GET /occasions
  # GET /occasions.json
  def index
    if current_user.organization.nil?
      redirect_to new_organization_path
    else
      @occasions = current_user.organization.occasions
    end
  end

  def all
    @occasions = Occasion.all
  end

  # GET /occasions/1
  # GET /occasions/1.json
  def show
  end

  # GET /occasions/new
  def new
    @occasion = current_user.organization.occasions.new
    @occasion.user = current_user
  end

  # GET /occasions/1/edit
  def edit
  end

  # POST /occasions
  # POST /occasions.json
  def create
    @occasion = current_user.organization.occasions.new(occasion_params)
    @occasion.user = current_user

    respond_to do |format|
      if @occasion.save
        format.html { redirect_to @occasion, notice: 'Occasion was successfully created.' }
        format.json { render :show, status: :created, location: @occasion }
      else
        format.html { render :new }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occasions/1
  # PATCH/PUT /occasions/1.json
  def update
    respond_to do |format|
      if @occasion.update(occasion_params)
        format.html { redirect_to @occasion, notice: 'Occasion was successfully updated.' }
        format.json { render :show, status: :ok, location: @occasion }
      else
        format.html { render :edit }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occasions/1
  # DELETE /occasions/1.json
  def destroy
    @occasion.destroy
    respond_to do |format|
      format.html { redirect_to occasions_url, notice: 'Occasion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occasion
      @occasion = Occasion.find(params[:id])
    end

    def check_owner
      unless current_user == @occasion.user 
        redirect_to @occasion
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def occasion_params
      params.require(:occasion).permit(:name, :description, :venue, :date, :time_start, :time_end, :latitude, :longitude, :user_id)
    end
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/_form.html.erb
<%= form_for(@occasion, html: {autocomplete: 'off', class: 'col l12'}) do |f| %> 
  <% if @occasion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@occasion.errors.count, "error") %> prohibited this occasion from being saved:</h2>

      <ul>
      <% @occasion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <style>
      #map {
        height: 400px;
      }
    </style>
     
<!-- <div class="col-sm-offset-3 col-sm-6"> -->
<div class="panel panel-violet">
  <div class="panel-heading">Create Occasion</div>
    <div class="panel-body pan">
        <div class="form-body pal">
          
              <div class="form-group">
                <div class="input-icon right">
                  <%= f.text_field :name, autocomplete: 'off', class: 'validate form-control', placeholder: 'Name' %>
                  </div>
                </div>

                <div class="form-group">
                  <div class="input-icon right">
                    <%= f.text_area :description, autocomplete: 'off', class: 'validate form-control', placeholder: 'Description' %></div>
                  </div>

                <div class="form-group">
                  <div class="input-icon right">
                    <%= f.text_field :venue, autocomplete: 'off', class: 'validate form-control', placeholder: 'Venue' %></div>
                  </div>

                <div class="form-group">
                  <div class="input-icon right">
                    <%= f.label :time_start %>
                    <%= f.datetime_select :time_start %></div>
                  </div>

                <div class="form-group">
                  <div class="input-icon right">
                    <%= f.label :time_end %>
                    <%= f.datetime_select :time_end %></div>
                  </div>
                </div>         

    <%= f.text_field :latitude, hidden: false, class: 'form-control' %>
    <%= f.text_field :longitude, hidden: false, class: 'form-control' %>
    <br/>

<input placeholder="Find Places" id="map_input" type="text" hidden style="right:100px" class="col s8">
<div id="map" class="col s12"></div>

</div>
                <div class="form-actions text-center pal">
                  <%= f.submit class: 'btn btn-primary' %>
                  </div>

<% end %>
</div>
</div>

<!-- <div id="us2" style="width: 500px; height: 400px;"></div> -->
    <script>
      var map;
      var marker;
      var user_lat;
      var user_long;
      var userLatLong;
      // var contentString;

      function getLocation() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(showPosition);
        } else {
          alert("Geolocation is not supported by this browser.");
        }
      }

      function showPosition(position){
        user_lat =  position.coords.latitude;
        user_long = position.coords.longitude;
        userLatLong = {lat: user_lat, lng: user_long};
        initMap();
      }

      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: userLatLong
        });

        marker = new google.maps.Marker({
          position: userLatLong,
          map: map,
          draggable: true,
          title: 'You are Here'
        });

        // Create the search box and link it to the UI element.
          var input = document.getElementById('map_input');
          var searchBox = new google.maps.places.SearchBox(input);
          map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

          searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }
          console.log('places_changed')
          // Clear out the old markers.
            marker.setMap(null);

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {

            // Create a marker for each place.
            marker = new google.maps.Marker({
              map: map,
              title: place.name,
              position: place.geometry.location
            });
            updateLatLng(marker.getPosition());

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        });

        // var infowindow = new google.maps.InfoWindow({
        //   content: "<p>UNIVERSITI ISLAM</p>"+"<p>ANTARABANGSA MALAYSIA</p>",
        // });

        marker.addListener('click', function() {
        infowindow.open(map, marker);
        });

        marker.addListener('dragend', function(e) {
        console.log("Latitude: " + e.latLng.lat() + "\r\nLongitude: " + e.latLng.lng());
        updateLatLng(e.latLng);
        });

        google.maps.event.addListener(map, 'click', function (e) {
                console.log("Latitude: " + e.latLng.lat() + "\r\nLongitude: " + e.latLng.lng());
                placeMarker(e.latLng);
                updateLatLng(e.latLng);

            });

        function placeMarker(location) {
          marker.setPosition(location);
        }


        // map.addListener('click', function(e) {
        //   console.log(e.getPosition())
        // });

        $('#map_input').show();
      }

      function updateLatLng(latLng){
        $('#occasion_latitude').val(latLng.lat());
        $('#occasion_longitude').val(latLng.lng());
      }

      getLocation();

      // $('#occasion_latitude').val(user_lat)
      // $('#occasion_longitude').val(user_long)

      //   console.log(position)

        // $('#us2').locationpicker({
        //   location: {latitude: user_lat, longitude: user_long}, 
        //   radius: 20,
        //   inputBinding: {
            // latitudeInput: $('#occasion_latitude'),
            // longitudeInput: $('#occasion_longitude'),
            // locationNameInput: $('#occasion_venue')
          // }
        // });
      // }
      // getLocation();      

    // var map;
    // $(".placepicker").placepicker({
    // placeChanged: function(place) {
    //   $('#occasion_latitude').val(this.getLocation().latitude)
    //   $('#occasion_longitude').val(this.getLocation().longitude)
    //   $('#occasion_venue').val(place.formatted_address)
    // }
  // });
  
    </script>

app/views/occasions/all.html.erb
<!--BEGIN PAGE WRAPPER-->
<div id="page-wrapper" style="<%= 'margin: 0' if !user_signed_in? %>">
<!--BEGIN CONTENT-->
<div class="page-content">

<p id="notice"><%= notice %></p>


  <div class="panel panel-green">
    <div class="panel-heading">My Events</div>
      <div class="panel-body">

        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Venue</th>
              <th>Time Start</th>
              <th>Time End</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @occasions.each do |occasion| %>
              <tr>
                <td><%= occasion.name %></td>
                <td><%= occasion.description %></td>
                <td><%= occasion.venue %></td>
                <td><%= occasion.time_start %></td>
                <td><%= occasion.time_end %></td>
                <td><%= link_to 'Show', occasion %></td>
                <td><%= link_to 'Edit', edit_occasion_path(occasion) %></td>
                <td><%= link_to 'Remove', occasion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'Add Occasion', new_occasion_path, class: "btn btn-primary col-md-offset-5" %>
      </div>     

    </div>
 

<br>



</div>
</div>

app/views/occasions/edit.html.erb
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="<%= 'margin: 0' if !user_signed_in? %>">  

<h1>Editing Occasion</h1>

<%= render 'form' %>

<%= link_to 'Show', @occasion %> |
<%= link_to 'Back', occasions_path %>

</div>

app/views/occasions/index.html.erb
  <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="<%= 'margin: 0' if !user_signed_in? %>">     
    
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
        <li class="active">Icons</li>
      </ol>
    </div><!--/.row-->

<p id="notice"><%= notice %></p>


  <div class="panel panel-green">
    <div class="panel-heading">My Events</div>
      <div class="panel-body">

        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Venue</th>
              <th>Time Start</th>
              <th>Time End</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @occasions.each do |occasion| %>
              <tr>
                <td><%= occasion.name %></td>
                <td><%= occasion.description %></td>
                <td><%= occasion.venue %></td>
                <td><%= occasion.time_start %></td>
                <td><%= occasion.time_end %></td>
                <td><%= link_to 'Show', occasion %></td>
                <td><%= link_to 'Edit', edit_occasion_path(occasion) %></td>
                <td><%= link_to 'Remove', occasion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'Add Occasion', new_occasion_path, class: "btn btn-primary col-md-offset-5" %>
      </div>     

    </div>
 

<br>



</div>

app/views/occasions/new.html.erb
  <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="<%= 'margin: 0' if !user_signed_in? %>">     
    
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
        <li class="active">Icons</li>
      </ol>
    </div><!--/.row-->

<div class= "row">
<%= render 'form' %>

<%= link_to 'Back', occasions_path %>
</div>
</div>

app/views/occasions/show.html.erb
  <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="<%= 'margin: 0' if !user_signed_in? %>">     
    
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
        <li class="active">Icons</li>
      </ol>
    </div><!--/.row-->

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @occasion.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @occasion.description %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @occasion.venue %>
</p>

<p>
  <strong>Time Start:</strong>
  <%= @occasion.time_start %>
</p>

<p>
  <strong>Time End:</strong>
  <%= @occasion.time_end %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @occasion.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @occasion.longitude %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= @occasion.organization.name %>
</p>

<%= link_to 'Edit', edit_occasion_path(@occasion) %> |
<%= link_to 'Back', occasions_path %>

    <style>
      #map {
        height: 400px;
      }
    </style>

    <br/>

<div id="map" class="col s12"></div>

<script>
      var map;
      var marker;
      var user_lat;
      var user_long;
      var userLatLong;
      // var contentString;

      // function getLocation() {
      //   if (navigator.geolocation) {
      //     navigator.geolocation.getCurrentPosition(showPosition);
      //   } else {
      //     alert("Geolocation is not supported by this browser.");
      //   }
      // }

      function showPosition(position){
        user_lat =  <%= @occasion.latitude %>;
        user_long = <%= @occasion.longitude %>;
        userLatLong = {lat: user_lat, lng: user_long};
        initMap();
      }

      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: userLatLong
        });

        marker = new google.maps.Marker({
          position: userLatLong,
          map: map,
        });

        // // Create the search box and link it to the UI element.
        //   var input = document.getElementById('map_input');
        //   var searchBox = new google.maps.places.SearchBox(input);
        //   map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        //   searchBox.addListener('places_changed', function() {
        //   var places = searchBox.getPlaces();

        //   if (places.length == 0) {
        //     return;
        //   }
        //   console.log('places_changed')
        //   // Clear out the old markers.
        //     marker.setMap(null);

        //   // For each place, get the icon, name and location.
        //   var bounds = new google.maps.LatLngBounds();
        //   places.forEach(function(place) {

        //     // Create a marker for each place.
        //     marker = new google.maps.Marker({
        //       map: map,
        //       title: place.name,
        //       position: place.geometry.location
        //     });
        //     updateLatLng(marker.getPosition());

        //     if (place.geometry.viewport) {
        //       // Only geocodes have viewport.
        //       bounds.union(place.geometry.viewport);
        //     } else {
        //       bounds.extend(place.geometry.location);
        //     }
        //   });
        //   map.fitBounds(bounds);
        // });

        // var infowindow = new google.maps.InfoWindow({
        //   content: "<p>UNIVERSITI ISLAM</p>"+"<p>ANTARABANGSA MALAYSIA</p>",
        // });

        marker.addListener('click', function() {
        infowindow.open(map, marker);
        });

        // marker.addListener('dragend', function(e) {
        // console.log("Latitude: " + e.latLng.lat() + "\r\nLongitude: " + e.latLng.lng());
        // updateLatLng(e.latLng);
        // });

        // google.maps.event.addListener(map, 'click', function (e) {
        //         console.log("Latitude: " + e.latLng.lat() + "\r\nLongitude: " + e.latLng.lng());
        //         placeMarker(e.latLng);
        //         updateLatLng(e.latLng);

        //     });

        function placeMarker(location) {
          marker.setPosition(location);
        }


        // map.addListener('click', function(e) {
        //   console.log(e.getPosition())
        // });

        // $('#map_input').show();
      }

      // function updateLatLng(latLng){
      //   $('#occasion_latitude').val(latLng.lat());
      //   $('#occasion_longitude').val(latLng.lng());
      // }

      showPosition();
  
    </script>

</div>