config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :todo_lists do
    member do
      post 'add_todo_item'
      delete 'todo_item/:todo_item_id' => "todo_lists#destroy_todo_item", as: :todo_item
    end
  end
  resources :organizations
  resources :occasions do
    collection do
      get 'all'
    end
  end
  devise_for :users
  get "dashboard/" => "dashboard#index"
  get "fmodel/" => "fmodel#index"
  get "form_build/" => "form_build#index"
  root "welcome#index"

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :user
  has_many :occasions
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  # GET /organizations
  # GET /organizations.json
  def index
    if current_user.organization.nil?
      redirect_to new_organization_path
    else
      @organization = current_user.organization
    end
  end

  def show
    if current_user.organization.nil?
      redirect_to new_organization_path
    else
      @organization = current_user.organization
    end
  end

  # GET /organizations/new
  def new
    @organization = current_user.organization || current_user.build_organization
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = current_user.build_organization(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :index, status: :created}
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organizations_path, notice: 'Organization was successfully updated.' }
        format.json { render :index, status: :ok}
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = current_user.organization
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :reg_no, :street, :city, :postcode, :state, :country, :status, :user_id)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :reg_no %><br>
    <%= f.text_field :reg_no %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
  <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="<%= 'margin: 0' if !user_signed_in? %>">     
    
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
        <li class="active">Icons</li>
      </ol>
    </div><!--/.row-->

<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

</div>

app/views/organizations/index.html.erb
  <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="<%= 'margin: 0' if !user_signed_in? %>">     
    
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
        <li class="active">Icons</li>
      </ol>
    </div><!--/.row-->

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Reg no:</strong>
  <%= @organization.reg_no %>
</p>

<p>
  <strong>Street:</strong>
  <%= @organization.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @organization.city %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @organization.postcode %>
</p>

<p>
  <strong>State:</strong>
  <%= @organization.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @organization.country %>
</p>

<p>
  <strong>Status:</strong>
  <%= @organization.status %>
</p>


<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', occasions_path %>

</div>

app/views/organizations/new.html.erb
  <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="<%= 'margin: 0' if !user_signed_in? %>">     
    
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
        <li class="active">Icons</li>
      </ol>
    </div><!--/.row-->
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>
</div>
</div>

app/views/organizations/show.html.erb
 <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main" style="<%= 'margin: 0' if !user_signed_in? %>">     
    
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
        <li class="active">Icons</li>
      </ol>
    </div><!--/.row-->

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Reg no:</strong>
  <%= @organization.reg_no %>
</p>

<p>
  <strong>Street:</strong>
  <%= @organization.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @organization.city %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @organization.postcode %>
</p>

<p>
  <strong>State:</strong>
  <%= @organization.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @organization.country %>
</p>

<p>
  <strong>Status:</strong>
  <%= @organization.status %>
</p>

</div>