config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :todo_lists do
    member do
      post 'add_todo_item'
      delete 'todo_item/:todo_item_id' => "todo_lists#destroy_todo_item", as: :todo_item
    end
  end
  resources :organizations
  resources :occasions do
    collection do
      get 'all'
    end
  end
  devise_for :users
  get "dashboard/" => "dashboard#index"
  get "fmodel/" => "fmodel#index"
  get "form_build/" => "form_build#index"
  root "welcome#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable 
end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  validates :organization, presence: true
  validates :user, presence: true
  validates :name, presence: true
  belongs_to :organization
  belongs_to :user
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :user
  has_many :occasions
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  has_many :todo_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :occasions, through: :organization
  has_one :organization

  # optional features
  has_many :todo_lists
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@todo_list = current_user.todo_lists.where(title: "dashboard todo").first_or_create
  	@todo_items = @todo_list.todo_items.all
  end
end

app/controllers/fmodel_controller.rb
class FmodelController < ApplicationController
  def index
  	render layout: false
  end
end

app/controllers/form_build_controller.rb
class FormBuildController < ApplicationController
  def index
  	render layout: false
  end
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
  before_action :set_occasion, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, except: [:all, :show, :index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  # GET /occasions
  # GET /occasions.json
  def index
    if current_user.organization.nil?
      redirect_to new_organization_path
    else
      @occasions = current_user.organization.occasions
    end
  end

  def all
    @occasions = Occasion.all
  end

  # GET /occasions/1
  # GET /occasions/1.json
  def show
  end

  # GET /occasions/new
  def new
    @occasion = current_user.organization.occasions.new
    @occasion.user = current_user
  end

  # GET /occasions/1/edit
  def edit
  end

  # POST /occasions
  # POST /occasions.json
  def create
    @occasion = current_user.organization.occasions.new(occasion_params)
    @occasion.user = current_user

    respond_to do |format|
      if @occasion.save
        format.html { redirect_to @occasion, notice: 'Occasion was successfully created.' }
        format.json { render :show, status: :created, location: @occasion }
      else
        format.html { render :new }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occasions/1
  # PATCH/PUT /occasions/1.json
  def update
    respond_to do |format|
      if @occasion.update(occasion_params)
        format.html { redirect_to @occasion, notice: 'Occasion was successfully updated.' }
        format.json { render :show, status: :ok, location: @occasion }
      else
        format.html { render :edit }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occasions/1
  # DELETE /occasions/1.json
  def destroy
    @occasion.destroy
    respond_to do |format|
      format.html { redirect_to occasions_url, notice: 'Occasion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occasion
      @occasion = Occasion.find(params[:id])
    end

    def check_owner
      unless current_user == @occasion.user 
        redirect_to @occasion
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def occasion_params
      params.require(:occasion).permit(:name, :description, :venue, :date, :time_start, :time_end, :latitude, :longitude, :user_id)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy, :add_todo_item]
  protect_from_forgery :except => [:add_todo_item]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.new
  end

  def add_todo_item
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    respond_to do |format|
      if @todo_item.save
        format.html { render js: @todo_item.to_json, notice: 'Todo item was successfully added.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_todo_item
    @todo_list = TodoList.find(params[:id])
    @todo_item = @todo_list.todo_items.find(params[:todo_item_id])
    @todo_item.destroy
    respond_to do |format|
      format.html { render json: nil, status: :ok, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@occasions = Occasion.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/fmodel_helper.rb
module FmodelHelper
end

app/helpers/form_build_helper.rb
module FormBuildHelper
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span>Events</span>Bhai</a>
                <ul class="user-menu">
                    <li class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"></svg><%= user_signed_in? ? ((image_tag avatar_url(current_user, 20)).html_safe + current_user.email) : "User" %><span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Profile</a></li>
                            <li><a href="#"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Settings</a></li>
                            <li><a>
                                <% if user_signed_in? %>
                                    <%= link_to( '<svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg>&nbsp'.html_safe + 'Logout', destroy_user_session_path, :method => :delete) %>
                                <% else %>
                                    <%= link_to('<svg class="glyph stroked key "><use xlink:href="#stroked-key"/></svg>&nbsp'.html_safe + 'Login', new_user_session_path)  %>  
                                <% end %>
                            </a></li>
                        </ul>
                    </li>
                </ul>
            </div>
                            
        </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/_sidebar.html.erb
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <form role="search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
            </div>
        </form>
        <ul class="nav menu">
        
        <%= render partial: 'layouts/sidebar_link',
        locals: {
            path: dashboard_path,
            title: " Dashboard",
            icon: "dashboard-dial"
            } %>

            <li><a href="<%= root_path %>"><svg class="glyph stroked location pin"><use xlink:href="#stroked-location-pin"></use></svg> Events & Locations</a></li>

            <li><a href="<%= occasions_path %>"><svg class="glyph stroked table"><use xlink:href="#stroked-table"></use></svg> My Events</a></li>

            <li><a href="<%= organizations_path %>"><svg class="glyph stroked app window with content"><use xlink:href="#stroked-app-window-with-content"/></use></svg> My Organization</a></li>


    </div><!--/.sidebar-->

app/views/layouts/_sidebar_link.html.erb
<li class="<%= 'active' if request.env['PATH_INFO'] == path %>">
	<a href="<%= path %>">
	<svg class="glyph stroked <%= icon %>">
	<use xlink:href="#stroked-<%= icon %>"></use>
    </svg><%= title %></a></li>
	</i>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Event</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <script type="text/javascript" src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
    <!--Icons-->
    <script src="/assets/lumino.glyphs.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
    <% if user_signed_in? %>
        <%= render 'layouts/sidebar' %>
    <%end%>
    <%= yield %>


    <script src="/assets/jquery-1.11.1.min.js"></script>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/bootstrap-datepicker.js"></script>
    <script>
        $('#calendar').datepicker({
        });

        !function ($) {
            $(document).on("click","ul.nav li.parent > a > span.icon", function(){          
                $(this).find('em:first').toggleClass("glyphicon-minus");      
            }); 
            $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
        }(window.jQuery);

        $(window).on('resize', function () {
          if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
        })
        $(window).on('resize', function () {
          if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
        })
    </script>   

</body>
</html>